name: Lint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy
      - name: Install pytest
        run: pip install pytest
      - name: Run mypy
        run: py.test --mypy --ignore=work
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}